profiles = new Array(
"|, John Garnett, R&D Director, Disruptive Innovation, ConAgra Foods||||||||||||./prof/prof2264.html",
"Acid Copolymer Adhesive - More than Just a Tie Layer...|Acid Copolymer Adhesive - More than Just a Tie Layer, Otto Plassman, INEOS Olefins & Polymers Europe||||||||||||./prof/prof2263.html",
"Adhesion in Extrusion Coating - Time in the Air Gap Rev...|Adhesion in Extrusion Coating - Time in the Air Gap Revisited, Barry A. Morris, DuPont Packaging & Industrial Polymers||||||||||||./prof/prof2218.html",
"Advanced Techniques for Integrating Brand-Authenticatin...|Advanced Techniques for Integrating Brand-Authenticating DNA into Point-of-Sale Packaging Materials, Steve Helker, ITW Pillar Technologies||||||||||||./prof/prof2212.html",
"Advances in LDPE Resins for Extrusion Coating Applicati...|Advances in LDPE Resins for Extrusion Coating Applications, Michael Biscoglio, The Dow Chemical Company||||||||||||./prof/prof2217.html",
"Baldwin Technologies...|Baldwin Technologies, James Daly, Baldwin Technology||||||||||||./prof/prof2237.html",
"Biopolymers for Paperboard Extrusion Coating and Conver...|Biopolymers for Paperboard Extrusion Coating and Converting, C. Carey Yang, WestRock Company||||||||||||./prof/prof2230.html",
"Celanese Improved Adhesion Ateva® ExtruBond™ EVA for Ex...|Celanese Improved Adhesion Ateva® ExtruBond™ EVA for Extrusion Coating - Extrusion Lamination, James T. Jones, EVA Polymers||||||||||||./prof/prof2234.html",
"Cemented Tungsten Carbide Tooling and Wear Parts for th...|Cemented Tungsten Carbide Tooling and Wear Parts for the Flexible Packaging and Converting Industry, David LeMaistre, Crafts Technology||||||||||||./prof/prof2221.html",
"Challenges of Winding Flexible Packaging Films...|Challenges of Winding Flexible Packaging Films, R. Duane Smith, Davis-Standard LLC||||||||||||./prof/prof2220.html",
"Coating Trial of an Antimicrobial Coating Containing Ni...|Coating Trial of an Antimicrobial Coating Containing Nisin Using a Large Scale Gravure Application Process, Duncan Darby PhD, Clemson University||||||||||||./prof/prof2253.html",
"Collaboration - A New Material in an Unexpected Applica...|Collaboration - A New Material in an Unexpected Application, Norman Aubee, NOVA Chemicals||||||||||||./prof/prof2265.html",
"Design, Operation, and Maintenance of an Internally Dec...|Design, Operation, and Maintenance of an Internally Deckled Extrusion Coating Die, Gary Oliver, (on behalf of) Nordson Extrusion Dies Industries||||||||||||./prof/prof2259.html",
"Development of Low-Barrier Packaging Structure for Micr...|Development of Low-Barrier Packaging Structure for Microwave Assisted Pasteurization Processes (MAPS), Kanishka Bhunia, Washington State University||||||||||||./prof/prof2252.html",
"Development of PGA Barrier Polymer at VTT...|Development of PGA Barrier Polymer at VTT, Jouni Lattu, VTT Technical Research Centre of Finland Ltd.||||||||||||./prof/prof2251.html",
"Effect of Formulation and Processing on the Properties ...|Effect of Formulation and Processing on the Properties of High Performance LLDPE in Heavy Duty Film Applications, Maged Botros Ph.D., LyondellBasell Industries||||||||||||./prof/prof2246.html",
"Effect of the Electrical Conductivities of Corona Disch...|Effect of the Electrical Conductivities of Corona Discharge Ground Rolls on Surface Treatment, Steve Helker, ITW Pillar Technologies||||||||||||./prof/prof2213.html",
"Effect on Nylon Copolymerization in Flexible Thermoform...|Effect on Nylon Copolymerization in Flexible Thermoforming, Sergi Salvà Sàez, UBE America Inc.||||||||||||./prof/prof2224.html",
"Enhanced Performance of Polylactide Shrink Films...|Enhanced Performance of Polylactide Shrink Films, Jim Nangeroni, NatureWorks LLC||||||||||||./prof/prof2228.html",
"Film Enhancement Utilizing Nano-Particulates in Multila...|Film Enhancement Utilizing Nano-Particulates in Multilayers Films Greater Than 25 Layers, Michael Taylor, Alpha Marathon Film Extrusion Technologies Inc.||||||||||||./prof/prof2232.html",
"Going Beyond Adhesion - the Dual Functionality of Tie L...|Going Beyond Adhesion - the Dual Functionality of Tie Layers, Yong Zheng, The Dow Chemical Company||||||||||||./prof/prof2262.html",
"Grease Resistant Multilayer Polyethylene Films...|Grease Resistant Multilayer Polyethylene Films, Shivendra Goyal, NOVA Chemicals Corporation||||||||||||./prof/prof2255.html",
"High Gas Barrier Coatings for Polyester Film...|High Gas Barrier Coatings for Polyester Film, Ginger Cushing, Michelman Inc.||||||||||||./prof/prof2256.html",
"High Performance Bio-Based Barrier Materials for Food P...|High Performance Bio-Based Barrier Materials for Food Packaging, Gene Medlock, Kuraray America, Inc.||||||||||||./prof/prof2229.html",
"Horizontal Ironing Roll Winder...|Horizontal Ironing Roll Winder, Lou Piffer, Davis-Standard||||||||||||./prof/prof2239.html",
"HUMECO-TEC(TM) - Technology for Sustainable Packaging D...|HUMECO-TEC(TM) - Technology for Sustainable Packaging Design, Dr. Daryl Basham, Humanitarian Scientific||||||||||||./prof/prof2241.html",
"Improved Adhesion EVA for Extrusion Coating-Extrusion L...|Improved Adhesion EVA for Extrusion Coating-Extrusion Laminating, Scott Weber, Celanese||||||||||||./prof/prof2247.html",
"Improvements in Productivity and Efficiency of Modern S...|Improvements in Productivity and Efficiency of Modern Solventless Adhesives, Larry Jopko, The Dow Chemical Company||||||||||||./prof/prof2261.html",
"Improving Hot Tack for Rim Seals...|Improving Hot Tack for Rim Seals, Sean Richards, LyondellBasell Industries||||||||||||./prof/prof2244.html",
"Innovation - Easy to Say, Hard to Do - an Innovation Mo...|Innovation - Easy to Say, Hard to Do - an Innovation Model That Works, John Homoelle, Michelman Inc.||||||||||||./prof/prof2243.html",
"Learning from Shear and Extensional Rheology of a few E...|Learning from Shear and Extensional Rheology of a few Extrusion Coating Polyethylenes, Olivier Catherine, Cloeren Incorporated||||||||||||./prof/prof2222.html",
"Liquid and Gas Barrier Coatings for Cellulose-Based Foo...|Liquid and Gas Barrier Coatings for Cellulose-Based Food Packaging, Alexander Bardenstein, Danish Technological Institute (DTI)||||||||||||./prof/prof2250.html",
"Nanoscale Barrier Coating on BOPP Packaging Film by ALD...|Nanoscale Barrier Coating on BOPP Packaging Film by ALD, Dr. Johanna Lahti, Tampere University of Technology||||||||||||./prof/prof2254.html",
"New Bio-Based Solutions for Paper and Packaging...|New Bio-Based Solutions for Paper and Packaging, Alicia Richards, AquaSol Corporation||||||||||||./prof/prof2235.html",
"New Formulations for Consistent Slip Properties...|New Formulations for Consistent Slip Properties, Dr. Bhushan Deshpande, Techmer PM, LLC||||||||||||./prof/prof2258.html",
"New HDPE Resins May Offer Film Improvements...|New HDPE Resins May Offer Film Improvements, Thomas J. Schwab, LyondellBasell Industries||||||||||||./prof/prof2249.html",
"New Sealants for Extrusion Coating...|New Sealants for Extrusion Coating, Apurva Shah, Dow||||||||||||./prof/prof2240.html",
"New Ultra Versatile Adhesive for Extrusion Lamination...|New Ultra Versatile Adhesive for Extrusion Lamination, Nick Khasat, Arkema Inc.||||||||||||./prof/prof2260.html",
"NOVA Chemicals - PE Products, Capability, Expertise...|NOVA Chemicals - PE Products, Capability, Expertise, Mike Cappelli, NOVA Chemicals||||||||||||./prof/prof2266.html",
"Peelable Seal Films with Enhanced Moisture Barrier Prop...|Peelable Seal Films with Enhanced Moisture Barrier Properties for Flexible Packaging Applications, Dan Falla, NOVA Chemicals Corporation||||||||||||./prof/prof2245.html",
"Physical Property Modeling of Multilayer Heavy Duty Sac...|Physical Property Modeling of Multilayer Heavy Duty Sack Films, Nancy Conley, NOVA Chemicals Corporation||||||||||||./prof/prof2216.html",
"PLACE Division - The Next Generation...|PLACE Division - The Next Generation, Jim Lush, PLACE Division||||||||||||./prof/prof2242.html",
"Polyethylene, Acid Copolymer and Ionomer Sealants on Al...|Polyethylene, Acid Copolymer and Ionomer Sealants on Aluminum Foil - What Really Makes Them Different, Guenter Schubert, Hydro Aluminum Rolled Products GmbH||||||||||||./prof/prof2226.html",
"Processing of Metallocenes in Extrusion Coating Applica...|Processing of Metallocenes in Extrusion Coating Applications, Christine Ronaghan, Cloeren Incorporated||||||||||||./prof/prof2223.html",
"Roll-to-Roll Coating of Nanocellulosic Barriers on Pape...|Roll-to-Roll Coating of Nanocellulosic Barriers on Paper, Martti Toivakka, Åbo Akademi University||||||||||||./prof/prof2231.html",
"Seal-Through-Contamination and 'Caulkability' - An Eval...|Seal-Through-Contamination and 'Caulkability' - An Evaluation of Sealants’ Ability to Encapsulate Contaminants in the Seal Area, Daniel Ward, NOVA Chemicals||||||||||||./prof/prof2219.html",
"Test Methods for Evaluating Grease and Mineral Oil Barr...|Test Methods for Evaluating Grease and Mineral Oil Barriers, Dr. Mika Vähä-Nissi, VTT Technical Research Centre of Finland Ltd.||||||||||||./prof/prof2248.html",
"Testing and Predicting Impact Puncture Resistance of Mu...|Testing and Predicting Impact Puncture Resistance of Multilayer Flexible Packaging Films, Barry A. Morris, DuPont Packaging & Industrial Polymers||||||||||||./prof/prof2225.html",
"The Addivant Solution for the Production of Nonylphenol...|The Addivant Solution for the Production of Nonylphenol-Free PE Flexible Packaging, Ronald Becker, Addivant||||||||||||./prof/prof2238.html",
"The Effect of Paperboard Coating Treatments on Polyethy...|The Effect of Paperboard Coating Treatments on Polyethylene Adhesion During Extrusion Coating, Part 1 - Paperboard Coatings, Don Ventresca, Trinseo LLC||||||||||||./prof/prof2214.html",
"The Effect of Paperboard Coating Treatments on Polyethy...|The Effect of Paperboard Coating Treatments on Polyethylene Adhesion During Extrusion Coating, Part 2 - Extrusion Coating Study, Kelly Frey, Chevron Phillips Chemical Company LLC||||||||||||./prof/prof2215.html",
"Welcome to the Revolution - The Next Generation of Sust...|Welcome to the Revolution - The Next Generation of Sustainable Materials Beyond Paper, Sean Ireland, Imerys||||||||||||./prof/prof2233.html"
);
